# Generated by Django 4.0.3 on 2023-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_api', '0004_notemodel_timestamp_alter_notemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='title',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
