# Generated by Django 4.0.3 on 2023-03-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_api', '0006_alter_notemodel_timestamp_alter_notemodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='timestamp',
            new_name='timestamped',
        ),
    ]
