# Generated by Django 4.0.3 on 2023-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_api', '0003_alter_notemodel_topic_alter_notemodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='timestamp',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
