# Generated by Django 4.0.3 on 2023-03-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_api', '0009_notemodel_currenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='currentTime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
